spring:
  datasource:
    url: jdbc:mysql://localhost:3306/postgraduate?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: root